version: '3.6'

services:
  postgres:
    container_name: subscription-postgres
    image: postgres:14.6-alpine
    environment:
      POSTGRES_DB: subscription
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: always
    ports:
      - 5432:5432
  
  redis:
    image: redis:7.2.4
    restart: always
    container_name: subscription-redis
    ports:
      - 6379:6379

networks:
  vnet:
    driver: bridge
